### ISSUE TITLE
Help with `non-exhaustive patterns` error

### ISSUE THREAD

**Issue by joshmarlow** [fflorent/nom_locate#19]
@fflorent I just discovered your project and from the docs, it appears to be exactly what I'm looking for! Thank you for this contribution to the community.

However, I'm having some trouble integrating it into my project.  When I add it to my project (which builds using `nom` 4.0.0), I get the following errors:

```
error[E0004]: non-exhaustive patterns: `Error(List(_))` not covered
   --> /home/joshmarlow/.cargo/registry/src/<REDACTED>/nom_locate-0.3.1/src/lib.rs:299:23
    |
299 |                 match e {
    |                       ^ pattern `Error(List(_))` not covered

error[E0004]: non-exhaustive patterns: `Error(List(_))` not covered
   --> /home/joshmarlow/.cargo/registry/src/<REDACTED>/nom_locate-0.3.1/src/lib.rs:324:23
    |
324 |                 match e {
    |                       ^ pattern `Error(List(_))` not covered

error: aborting due to 2 previous errors
```

Do you have any thoughts about what the cause might be for this?

Thanks!

**Comment by ProgVal** [comment]
Hi and thanks! :)

You compiled `nom` with the `verbose-errors` feature, so you have to use that feature with `nom_locate` as well
