### ISSUE TITLE
using escaped_transform!(...)

### ISSUE THREAD

**Issue by transistorfet** [fflorent/nom_locate#13]
I'm having troubles getting code to compile that uses nom_locate's LocatedSpan and nom's escaped_transform!(...) macro.  I'm getting 4 type errors between &[u8] and LocatedSpan<&[u8]> with the following code:

```
named!(string_contents(Span) -> AST,
    map!(
        escaped_transform!(is_not!("\"\\"), '\\',
            alt!(
                tag!("\\") => { |_| &b"\\"[..] } |
                tag!("\"") => { |_| &b"\""[..] } |
                tag!("n")  => { |_| &b"\n"[..] } |
                tag!("r")  => { |_| &b"\r"[..] } |
                tag!("t")  => { |_| &b"\t"[..] }
            )
        ),
        |s| AST::String(String::from_utf8_lossy(&s).into_owned())
    )
);
```
I'm using rust 1.23.0 stable with nom 3.2.1 and nom_locate 0.1.1.  Do you have any insight?  Thanks

**Comment by fflorent** [comment]
I suspect that you cannot use `&s` as is but rather `&s.fragment`.

But I miss lot of context to help. Could you provide the compilation error?
Also it would be even great if your project is on github to provide a link in order to investigate.

Florent

**Comment by transistorfet** [comment]
Sorry, the errors were kind of long and not terribly helpful, but I've pasted them below.  The project is https://github.com/transistorfet/molten and the code in question is in src/parser.rs:736.  If you uncomment that block, and comment out the alternate "string" parser on line 762, you should be able to reproduce the errors (I didn't want to commit broken code).  It should also be possible to take the code snippet above, replace the AST references with just a String, and put it in the nom_locate example program to reproduce.

The above parser works fine if using &[u8] as input instead of Span, but I suspect there is an issue with how escaped_transform is defined as taking &[T] specifically, and breaking it into T.  I could use &[u8] for that one subparser and send it s.fragment, but I'm concerned about adjusting the remaining input once that parser returns.  I'm not all the familiar with the internals of nom.  I'll just have to spend a bit more time digging into it.

```
error[E0308]: mismatched types
   --> src/parser.rs:735:1
    |
735 | / named!(string_contents(Span) -> AST,
736 | |     map!(
737 | |         escaped_transform!(is_not!("\"\\"), '\\',
738 | |             alt!(
...   |
749 | |     )
750 | | );
    | |__^ expected &[u8], found struct `nom_locate::LocatedSpan`
    |
    = note: expected type `&[u8]`
               found type `nom_locate::LocatedSpan<&[u8]>`
    = note: this error originates in a macro outside of the current crate

error[E0308]: mismatched types
   --> src/parser.rs:735:1
    |
735 | / named!(string_contents(Span) -> AST,
736 | |     map!(
737 | |         escaped_transform!(is_not!("\"\\"), '\\',
738 | |             alt!(
...   |
749 | |     )
750 | | );
    | |__^ expected struct `nom_locate::LocatedSpan`, found &[u8]
    |
    = note: expected type `nom_locate::LocatedSpan<&[u8]>`
               found type `&[u8]`
    = note: this error originates in a macro outside of the current crate

error[E0308]: mismatched types
   --> src/parser.rs:735:1
    |
735 | / named!(string_contents(Span) -> AST,
736 | |     map!(
737 | |         escaped_transform!(is_not!("\"\\"), '\\',
738 | |             alt!(
...   |
749 | |     )
750 | | );
    | |__^ expected struct `nom_locate::LocatedSpan`, found &[u8]
    |
    = note: expected type `std::vec::Vec<nom::Err<nom_locate::LocatedSpan<&[u8]>, _>>`
               found type `std::vec::Vec<nom::Err<&[u8], _>>`
    = note: this error originates in a macro outside of the current crate

error[E0308]: mismatched types
   --> src/parser.rs:735:1
    |
735 | / named!(string_contents(Span) -> AST,
736 | |     map!(
737 | |         escaped_transform!(is_not!("\"\\"), '\\',
738 | |             alt!(
...   |
749 | |     )
750 | | );
    | |__^ expected struct `nom_locate::LocatedSpan`, found &[u8]
    |
    = note: expected type `nom::Err<nom_locate::LocatedSpan<&[u8]>, u32>`
               found type `nom::Err<&[u8], _>`
    = note: this error originates in a macro outside of the current crate

error[E0308]: mismatched types
   --> src/parser.rs:735:1
    |
735 | / named!(string_contents(Span) -> AST,
736 | |     map!(
737 | |         escaped_transform!(is_not!("\"\\"), '\\',
738 | |             alt!(
...   |
749 | |     )
750 | | );
    | |__^ expected struct `nom_locate::LocatedSpan`, found &[u8]
    |
    = note: expected type `nom_locate::LocatedSpan<&[u8]>`
               found type `&[u8]`
    = note: this error originates in a macro outside of the current crate

error: aborting due to 5 previous errors
```

**Comment by ProgVal** [comment]
I can't reproduce this issue; the following code works fine on `nom_locate` 0.3.0:

```rust
use nom::Needed;                                    
type Span<'a> = LocatedSpan<&'a [u8]>;              
named!(string_contents(Span) -> String,             
    map!(                                           
        escaped_transform!(is_not!("\"\\"), '\\',   
            alt!(                                   
                tag!("\\") => { |_| &b"\\"[..] } |  
                tag!("\"") => { |_| &b"\""[..] } |  
                tag!("n")  => { |_| &b"\n"[..] } |  
                tag!("r")  => { |_| &b"\r"[..] } |  
                tag!("t")  => { |_| &b"\t"[..] }    
            )                                       
        ),                                          
        |s| String::from_utf8_lossy(&s).into_owned()
    )                                               
);                                                  
```

**Comment by transistorfet** [comment]
I can confirm that upgrading to nom_locate 0.3 fixed the errors (after rewriting the parser for nom 4.0)

**Comment by fflorent** [comment]
Awesome!
